const Pdata = {
    products: [
        {
            name: 'Dessin',
            slug: 'dessin',
            category: 'Shirt',
            image: '/images/Pcarousel/dessin.png',
            price: 2000,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            countInStock: 20,
            description: 'A popular shirt',
        },

        {
            name: 'Copie double',
            slug: 'copie-double',
            category: 'Shirt',
            image: '/images/Pcarousel/copie-double-original.jpg',
            price: 3000,
            brand: 'Nike',
            rating: 3.5,
            numReviews: 10,
            countInStock: 20,
            description: 'A popular shirt',
        },

        {
            name: 'Destin de clandestin',
            slug: 'Destin-de-clandestin',
            category: 'Shirt',
            image: '/images/Pcarousel/DESTIN-DE-CLANDESTINS.jpg',
            price: 4000,
            brand: 'Raymond',
            rating: 5,
            numReviews: 10,
            countInStock: 20,
            description: 'A popular shirt',
        },

        {
            name: 'COPIE DOUBLE GRAND FORMAT',
            slug: 'copie-double-grand-format',
            category: 'Pants',
            image: '/images/Pcarousel/COPIE-DOUBLE-GRAND-FORMAT.jpg',
            price: 5000,
            brand: 'AllStar',
            rating: 4.5,
            numReviews: 10,
            countInStock: 20,
            description: 'Smart Looking',
        },

        {
            name: 'Classeur Tecno',
            slug: 'classeur-tecno',
            category: 'Pants',
            image: '/images/Pcarousel/CLASSEUR-TECNO.jpg',
            price: 6000,
            brand: 'Oliver',
            rating: 4.5,
            numReviews: 10,
            countInStock: 20,
            description: 'A popular Pants',
        },

        {
            name: 'Classeur',
            slug: 'classeur',
            category: 'Pants',
            image: '/images/Pcarousel/CLASSEUR.jpg',
            price: 7000,
            brand: 'Coka',
            rating: 4.5,
            numReviews: 10,
            countInStock: 20,
            description: 'A popular Pants',
        },

        {
            name: 'couleur',
            slug: 'couleur',
            category: 'Shirt',
            image: '/images/Pcarousel/dessin.png',
            price: 2000,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            countInStock: 20,
            description: 'A popular shirt',
        },

        {
            name: 'copie original',
            slug: 'copie-original',
            category: 'Shirt',
            image: '/images/Pcarousel/copie-double-original.jpg',
            price: 3000,
            brand: 'Nike',
            rating: 3.5,
            numReviews: 10,
            countInStock: 20,
            description: 'A popular shirt',
        },

        {
            name: 'Destin',
            slug: 'destin',
            category: 'Shirt',
            image: '/images/Pcarousel/DESTIN-DE-CLANDESTINS.jpg',
            price: 4000,
            brand: 'Raymond',
            rating: 5,
            numReviews: 10,
            countInStock: 20,
            description: 'A popular shirt',
        },

        {
            name: 'Copie grand',
            slug: 'copie-grand',
            category: 'Pants',
            image: '/images/Pcarousel/COPIE-DOUBLE-GRAND-FORMAT.jpg',
            price: 5000,
            brand: 'AllStar',
            rating: 4.5,
            numReviews: 10,
            countInStock: 20,
            description: 'Smart Looking',
        },

        {
            name: 'Tecno',
            slug: 'tecno',
            category: 'Pants',
            image: '/images/Pcarousel/CLASSEUR-TECNO.jpg',
            price: 6000,
            brand: 'Oliver',
            rating: 4.5,
            numReviews: 10,
            countInStock: 20,
            description: 'A popular Pants',
        },

        {
            name: 'Classic',
            slug: 'classic',
            category: 'Pants',
            image: '/images/Pcarousel/CLASSEUR.jpg',
            price: 7000,
            brand: 'Coka',
            rating: 4.5,
            numReviews: 10,
            countInStock: 20,
            description: 'A popular Pants',
        },
    ],
};
export default Pdata;
